### ISSUE TITLE
Support for virtual network peering

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-subnets#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

/cc @grayzu for visibility

### Description

This module would be more useful if it supported vnet peering. As you know due to limitations in AzureRM there are challenges doing this across subscriptions.

Suggest that AzAPI is used to create bi-directional peering to supplied resource ids.

### New or Affected Resource(s)/Data Source(s)

azapi_resource (Microsoft.Network/virtualNetworks/virtualNetworkPeerings)

### Potential Terraform Configuration

```hcl
module "subnets" {
  source = blah
  # ... existing input varibles
  virtual_network_peering = {
    to_hub = {
      remote_virtual_network_resource_id = "/subscriptions/..."
      create_outbound_peering_only       = true # do we create both sides of peering here?
      outbound_peering_name              = "" # optional, autogenerated using uuidv5
      inbound_peering_name               = "" # optional, autogenerated using uuidv5
      
      outbound_use_remote_gateways      = true
      inbound_use_remote_gateways       = true
      outbound_allow_forwarded_trafffic = true
      inbound_allow_forwarded_trafffic  = true
      outbound_allow_gateway_transit    = true
      inbound_allow_gateway_transit     = true
    }
  }
}
```

### References

This could be used by https://github.com/Azure/terraform-azure-modules/issues/8

**Comment by lonegunmanb** [comment]
Thanks @matt-FFFFFF for opening this issue, I'd like to create some new verified modules to provide different vnet peering topology, like [hub-spoke](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli) one.

[terraform-aws-vpc-peering](https://github.com/cloudposse/terraform-aws-vpc-peering) provided by CloudPosse would be a perfect example.

**Comment by matt-FFFFFF** [comment]
Hi @lonegunmanb 

I think H&S should be its own module. We should include azure firewall, route aggregation, etc. too.

I started an issue with a draft spec here:

https://github.com/Azure/terraform-azure-modules/issues/8

Happy to collaborate!
